### PR TITLE
Add 0.8 upgrade notification

### PR DESCRIPTION
**Pull request by soininen**
There is now a link on the Event log when Toolbox starts which opens a dialog notifying users about the up-and-coming 0.8 upgrade.

image

It is a well known fact that users do not read the Event log so this should not be too intrusive. We may want to make the notification more prominent once we have better estimate for the launch date, though.

Implements #2348

**Updated:** new screenshot to reflect changes in the text.

## Checklist before merging
- [x] Code has been formatted by black
- [x] Unit tests pass

### CODE REVIEW

**Comment by jkiviluo** [comment]
Maybe add a sentence saying that if you try out 0.8, take first copy of your project/DBs.

**Comment by soininen** [comment]
> Maybe add a sentence saying that if you try out 0.8, take first copy of your project/DBs.

That is a good idea! Done.

**Comment by PekkaSavolainen** [comment]
Looks good to me! Spotted one typo on second line: though -> thought

**Comment by soininen** [comment]
Big thanks to all reviewers!

**Pull request merged**
