### PR TITLE
Spine Toolbox changes related to ditching Dagster

### PR DESCRIPTION
**Pull request by PekkaSavolainen**
As per title.

To test Spine Toolbox without dagster, checkout branch `issue_2523`, make a fresh conda env and do `pip install -r requirements.txt`.

Re Issue #2523

## Checklist before merging
- [x] Documentation is up-to-date
- [x] Release notes have been updated
- [x] Unit tests have been added/updated accordingly
- [x] Code has been formatted by black
- [x] Unit tests pass

### CODE REVIEW

**Comment by PekkaSavolainen** [comment]
After a small edit, I'm not finding any problems here anymore. If anybody wants to check this out, it would be much appreciated. No need to check code if you're too busy, just execute a couple of projects and see if something doesn't look right. See install instructions above.

**Comment by soininen** [comment]
Stopping a Tool (tested with SpineOpt) does not seem to work. The hammer just keeps hammering and when I quit Toolbox, there is a rogue process that prevents Toolbox from shutting down properly.

**Comment by soininen** [comment]
Besides the above problem with stopping a workflow, I did not find anything of note. Nice work @manuelma and @PekkaSavolainen!

**Comment by soininen** [comment]
> Does this work a lot better with dagster?

Yes. I didn't run into similar problem with `0.8-dev`, though it isn't perfect, either.

**Comment by PekkaSavolainen** [comment]
Stopping execution depends on luck on 0.8-dev as well. Other times it works well but I just got this traceback after stopping SpineOpt in 0.8-dev branch.

```
Exception in thread Thread-30 (_wait_ping):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\data\GIT\SPINEENGINE\spine_engine\execution_managers\persistent_execution_manager.py", line 319, in _wait_ping
    data = conn.recv(1024)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

And there was a rogue python process after trying to quit toolbox that I needed to end in the task manager to actually close the app.

**Comment by PekkaSavolainen** [comment]
Ok I see the problem, Clicking Stop in the `jumpster` branch does actually interrupt the console successfully but this does not seem to be signaled over to the toolbox side, which causes the hammer to keep on hammering. I'll take a look.

**Comment by soininen** [comment]
We got the hammer problem fixed with @PekkaSavolainen. I believe we are now on par with the previous Dagster implementation.

**Comment by PekkaSavolainen** [comment]
I'll update the changelog and run black. Do you mind if I merge when I'm done?

**Comment by soininen** [comment]
> Do you mind if I merge when I'm done?

I suppose this is all the testing we're ever getting from this branch, so no, I do not mind.

**Pull request merged**
