### PR TITLE
Readme.md update

### LINKED ISSUE #2508: Update installation instructions in README
Move Python installation instructions (steps 1-3) from "Installation with Python and pipx" section to a new pre-installation section as it applies to both installation with pipx and installation from sources using Git. Mention in the beginning of the "Installation" that this pre-installation section is needed for pipx and source file installation alternatives (but not for the "Windows installation package" alternative).

Move Git installation step 4 from "Installation with Python and pipx" section to "Installation from sources using Git".

Add instructions to cd to the new Spine-Toolbox folder in "Installation from sources using Git."

### PR DESCRIPTION
**Pull request by PekkaSavolainen**
This PR updates Readme.md according to the issue description.

Fixes #2508

## Checklist before merging
- [x] Documentation is up-to-date
- [ ] Release notes have been updated
- [ ] Unit tests have been added/updated accordingly
- [ ] Code has been formatted by black
- [ ] Unit tests pass

### CODE REVIEW

**Comment by PekkaSavolainen** [comment]
@nhniina Is this good? You can preview the new readme.md in https://github.com/spine-tools/Spine-Toolbox/blob/issue_2508_readme_update/README.md

**Comment by nhniina** [comment]
Much better now. I would perhaps just add a few things (changes bolded):

- In _Installation_: "We provide three options for installing Spine Toolbox **(the first two options also require that you follow the Pre-installation steps)**:"
- In steps 1, 2 and 5 of _Installation from sources using Git_: Perhaps we can assume that anyone following these steps knows the cd command but it might still be safer to write "Use the cd command to change the working directory" instead of just writing "cd".
- In step 4 of _Installation from sources using Git_: "or on a Conda prompt **(if you are using a miniconda environment instead of venv)**"

Ignore the last suggestion if it doesn't matter if they are using miniconda or venv.

**Comment by PekkaSavolainen** [comment]
> Much better now. I would perhaps just add a few things (changes bolded):
> 
>     * In _Installation_: "We provide three options for installing Spine Toolbox **(the first two options also require that you follow the Pre-installation steps)**:"
> 
>     * In steps 1, 2 and 5 of _Installation from sources using Git_: Perhaps we can assume that anyone following these steps knows the cd command but it might still be safer to write "Use the cd command to change the working directory" instead of just writing "cd".
> 
>     * In step 4 of _Installation from sources using Git_: "or on a Conda prompt **(if you are using a miniconda environment instead of venv)**"
> 
> 
> Ignore the last suggestion if it doesn't matter if they are using miniconda or venv.

Thanks @nhniina! I did the suggested edits. Ok to merge now? I'll merge this to 0.8-dev and then cherry pick it to master so the readme's are the same on both.

**Comment by nhniina** [comment]
Yes, looks good now!

**Pull request merged**
