### PR TITLE
Redo move to pyproject.toml

### PR DESCRIPTION
**Pull request by suvayu**
This reverts commit adc54b774d7c155fc1e48ff6aaeca29ac9913d8d.

Attempt 2:
- move to `pyproject.toml` and
- use `setuptools_scm` & git tags for version management

Re #1934

## Checklist before merging
- [ ] ~Documentation is up-to-date~
- [ ] ~Release notes have been updated~
- [ ] ~Unit tests have been added/updated accordingly~
- [ ] ~Code has been formatted by black~
- [x] Unit tests pass

### CODE REVIEW

**Comment by suvayu** [comment]
Hmm, I'm more inclined towards updating the docs after we have tested the release script in `spine-conductor` more thoroughly. Then it can be updated in one go, explain the git based versioning changes, followed by the semi-automated release process that makes use of that.  WDYT?

**Comment by soininen** [comment]
> Hmm, I'm more inclined towards updating the docs after we have tested the release script in spine-conductor more thoroughly. 

I'm OK with that.

**Comment by PekkaSavolainen** [comment]
I pulled the ci branch from origin suvayu to branch 1934_automate_deployment, created a fresh python 3.10 conda environment, and did `pip install -r requirements.txt`. Seems to work fine. I guess the pyproject.toml conversion works well.

**Comment by PekkaSavolainen** [comment]
> Strange, the CI seems to fail on that branch with Python 3.8:
> 
> ```
> test_editor_sets_plain_value_in_parent_model (tests.widgets.test_ParameterValueEditor.TestParameterValueEditor) ... /home/runner/work/_temp/f7f42c08-42b9-430a-9dcc-2bc71acc9bb2.sh: line 4:  2962 Segmentation fault
> (core dumped) coverage run -m unittest discover --verbose
> Error: Process completed with exit code 139.
> ```

I updated requirements.txt, the tests should pass now. If the tests don't pass, we may have some extra @Slot decorator in there again.

**Comment by suvayu** [comment]
I just finished running them locally (with Python 3.8.17), they passed.

**Review by PekkaSavolainen — APPROVED** [review]

**Comment by PekkaSavolainen** [comment]
I approved these four  "Revert revert 'Move to pyproject.toml'" PR's. I tested them by doing a `pip install -r requirements.txt` to a fresh Python 3.10 miniconda envronment and it looked like things worked ok. Tests also pass, occasionally :).

I think it's up to @soininen if he wants to do the upcoming 0.7 release using the old setup.cfg config files or the new pyproject.toml config files.

btw, can we clean up the PR names please.

**Comment by soininen** [comment]
> I think it's up to @soininen if he wants to do the upcoming 0.7 release using the old setup.cfg config files or the new pyproject.toml config files.

This would be a good test for the feature, right? We should at least push out a release candidate or two to see if everything works as expected.

**Comment by suvayu** [comment]
I think we can do a release candidate after I implement the version pinning (of `spine*` packages) in the `conduct release` command. It should not be too difficult. I'll push more updates today, also for the docs.

**Comment by suvayu** [comment]
> btw, can we clean up the PR names please.

Done!

> Nice work @suvayu, this has been on our todo list for a long time.

Thank you, wouldn't have been possible without the input and testing from you and Antti :⁠-⁠)

**Comment by suvayu** [comment]
Now that the first pass on the documentation is done, I think all the `pyproject.toml` PRs final and ready.

I'll work on more windows testing for the `conduct release` command, and add a `publish` command. I should also add some upgrade docs, but not sure what would be the best place, README maybe?

**Comment by soininen** [comment]
> I should also add some upgrade docs, but not sure what would be the best place, README maybe?

If you mean upgrading `conduit`, then I guess its README.md would be the place.

**Comment by suvayu** [comment]
> If you mean upgrading `conduit`, then I guess its README.md would be the place.

No, I was referring to the problem Manuel asked about on Matrix, a user with an existing checkout, what do they need to do when upgrading, and what to do after future releases (so there's a new tag on GH, but not locally).

**Comment by PekkaSavolainen** [comment]
> > If you mean upgrading `conduit`, then I guess its README.md would be the place.
> 
> No, I was referring to the problem Manuel asked about on Matrix, a user with an existing checkout, what do they need to do when upgrading, and what to do after future releases (so there's a new tag on GH, but not locally).

Yes, the correct place for that would be in the **Installation from sources using Git** section in readme.md.

**Pull request merged**
